### ISSUE TITLE
On Wayland, examples panic with `Requested present mode Immediate is not in the list of supported present modes: [Mailbox, Fifo]`

### ISSUE THREAD

**Issue by mattdm** [Droggelbecher/bevy-fast-tilemap#10]
On Fedora Workstation, `cargo run --release --example iso` (or any of the other examples) gets me:

```
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Requested present mode Immediate is not in the list of supported present modes: [Mailbox, Fifo]
', /home/mattdm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:734:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
```

If I use `WINIT_UNIX_BACKEND=x11`, they work fine.

**Comment by Droggelbecher** [comment]
Hey @mattdm Thanks for the PR, can you make the dependency conditional on the platform as hinted at in https://github.com/Droggelbecher/bevy-fast-tilemap/pull/6 ? Alas, I have no linux dev machine accessible so I can not pick this up myself right now.

**Comment by Droggelbecher** [comment]
I can't check this right now, so closing this. If you're affected and reading this, don't hesitate to open a new issue.
