### ISSUE TITLE
Does it support 3D?

### ISSUE THREAD

**Issue by IvanKorchmit** [Droggelbecher/bevy-fast-tilemap#13]
Out of curiosity, does it support 3D camera orthographic projection? I'm struggling on how to display it in the world. Any tips will be appreciated!

By the way, this crate seems to be awesome!

**Comment by Droggelbecher** [comment]
Hm it should behave like any other 2d mesh in a 3d world, but havent tested that specifically. What problem do you encounter / what expectation wasnt met?

**Comment by IvanKorchmit** [comment]
> Hm it should behave like any other 2d mesh in a 3d world, but havent tested that specifically. What problem do you encounter / what expectation wasnt met?

Hello, I think my issue is that the tilemap doesn't get rendered and I have no idea why. So maybe 2d mesh can't be rendered by a 3d camera? For more context, I'm using an orthographic projection for my game.

**Comment by Droggelbecher** [comment]
Puh good question :) Can you share some minimal example code? Maybe I'll have time to play around with that a bit on the weekend

**Comment by sum-catnip** [comment]
yeah 2d meshed dont get rendered with a 3d camera in bevy

**Comment by Droggelbecher** [comment]
Oh ok, currently not intending to implement a (3d) material as well, but if somebody wants to get their hands dirty on this, I'd welcome the contribution.
