### ISSUE TITLE
Flipping tiles on an axis

### ISSUE THREAD

**Issue by cedtwo** [Droggelbecher/bevy-fast-tilemap#24]
Great library. I'm render a `Tiled` map and am unable to find any way to flip a tile on an axis. Does this a feature exist, or would implementing this feature be possible?

**Comment by Droggelbecher** [comment]
That should be possible with custom shader code. Lemme merge some WIP code for that and then i'll add an example on how to do it. Prolly next weekend-ish.

**Comment by Droggelbecher** [comment]
@cedtwo Can you check out the custom_shader_code example in 0.7.3? That should help with flipping tiles :)
