### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by urothis** [Droggelbecher/bevy-fast-tilemap#26]
I've been playing with this locally and wadding through a-lot of learning and wanted to create an issue to figure out if I'm heading in the correct direction/wasting my time because you're already working on this.

The simplest surface change from the shader context, looks to be changing the map_size to a vec3u, and adding a 'layer_padding/layer_offset' vec2f.

![isometric](https://github.com/Droggelbecher/bevy-fast-tilemap/assets/287208/501f7f67-df0e-4ea2-94bd-844a60d292cd)

Will donate this asset and my example I'm toying with, has some magical numbers.
https://gist.github.com/urothis/ba9eb3930dcc481c84fd10a6fc8d4e86

I assume the ideal would be to not over-complicate with additional logic for tile determinism and leave that up to build_and_initialize.

**Comment by Droggelbecher** [comment]
Hey @urothis I'm not quite following, solution to what? What problem are you trying to solve?

**Comment by urothis** [comment]
Apologies @Droggelbecher, I was working with stacking tilemaps to try and achieve some rct/ttd style terrain.

The performance scaling quickly became problematic, I assumed this was because I was doing multiple instances/entities.
With the next thought being that doing the layer/sprite culling in a single shader/entity/render pass seemed a much more optimal pattern.

**Comment by Droggelbecher** [comment]
Yeah indeed having really a lot of layers can be problematic at some point as your GPU has to do a lot of work to compute the depth/overlaps.
I think it could be done in the shader if you only render the surface of your 3d world and as you say have a per-tile y-offset or something. Still might become pretty expensive if for every pixel the shader has to check a lot of array entries to see whether a tile was lifted up to this particular position. There is probably some smarter approach and its not yet clear to me whether some parts of this computation might be better off being done on the CPU actually.
Perhaps this warrants a separate crate depending on how far you want to go down that path.

Depending on your game you also may not want to render a lot of different height levels at the same time as the occlusion of units etc.. can quickly become problematic (recently toyed with that a bit myself). Perhaps a viable option for you could be to only show a hand full of height layers at the same time (i.e. the ground and then some) which could help both the user and the machine ;-)
