### ISSUE TITLE
mistake in animation.rs example

### ISSUE THREAD

**Issue by Mergpijp** [Droggelbecher/bevy-fast-tilemap#30]
In the following code you build the map twice first with build_and_initialize for me this caused problems in the at function of map_indexer.  So I remoeved the last let map definition and add map.clone() to the spawn command since it will complain of moved value. Now the at function does not always return zero.

```
    let map = Map::builder(
        uvec2(64, 64),
        asset_server.load("pixel_tiles_16.png"),
        vec2(16., 16.),
    )
    .build_and_initialize(|m| {
        // Initialize using a closure
        // Set all tiles in layer 0 to index 4
        for y in 0..m.size().y {
            for x in 0..m.size().y {
                m.set(x, y, ((x + y) % 4 + 1) as u32);
            }
        }
    });

    commands.spawn(MapBundleManaged {
        material: materials.add(map),
        ..default()
    });

    let map = Map::builder(
        uvec2(64, 64),
        asset_server.load("pixel_tiles_16.png"),
        vec2(16., 16.),
    )
    .build();

    let bundle = MapBundleManaged {
        material: materials.add(map),
        transform: Transform::default().with_translation(vec3(0., 0., 1.)),
        ..default()
    };

    commands.spawn(bundle).insert(AnimationLayer);
```

**Comment by Droggelbecher** [comment]
Hey @Mergpijp , I have trouble understanding / reproducing the problem. What exactly is going wrong? What function returns zero? It should work perfectly fine to create two maps as is, if you give me more details about what goes wrong for you I can try and fix it at the source, thanks in advance!

**Comment by Mergpijp** [comment]
Hi, the function at of map indexer. what I did was not creating the two maps but just do 

`    let bundle = MapBundleManaged {
        material: materials.add(map),
        transform: Transform::default().with_translation(vec3(0., 0., 0.)),
        ..default()
    };
`
`commands.spawn(bundle).insert(AnimationLayer);`
why would you create two maps? I dont understand it. I will try with the new code of mine if it would work but it works with the adjusted code to.

**Comment by Droggelbecher** [comment]
Yeah i'm sure the adjusted code works, but it should also work to create multiple maps which may be desirable for some users.

Can you tell me more about your environment? Are you modifying the example in some way? For me the at function seems to work fine in animation.rs.

**Comment by Droggelbecher** [comment]
For layers use multiple maps or some custom shader logic. multiple maps can become slow if you end up drawing lots of overlapping quads for that, if you can, make most of them invisble for better performance.
