### ISSUE TITLE
inserting component to tile

### ISSUE THREAD

**Issue by Mergpijp** [Droggelbecher/bevy-fast-tilemap#36]
Hi,

Let say i have an enemy on a tile position the value is GRASS since it stands on grass. Is there a way to insert a component on the tile position? Or is this a limitation for not using ECS in this fast tilemap?

**Comment by Droggelbecher** [comment]
Its a limitation, what you can do is have your own MapPosition component for your entity and whenever that changes, update information to/from the map that youre interested in.

**Comment by Droggelbecher** [comment]
Instead of MapPosition use sonething like UVec2 in your example. Currently on phone, will send a more complete example later today

**Comment by Droggelbecher** [comment]
Ok here it goes.
Lets say your have some entities (in your case enemies) for which you want to:
- Track their position on the map
- Update their Transform accordingly (because they are sprites or something similar)
- Enrich them with the information which map tile they stand on (lets say for this example that defines how much cover they have and thus how easy they are to hit)

```rust
// Position of our entities on the map.
// This is the one that we want to work with, anything else will be derived from this automatically by below systems
#[derive(Component)]
pub struct MapPosition { position: UVec2; }

#[derive(Component)]
pub enum CoverType { GRASS, ROCK, NONE }

// Set transform from map data
fn update_position(
  mut entities: Query<(&MapPosition, &mut Transform), Changed<MapPosition>>,
  map_layers: Query<&Handle<Map>>,
  mut materials: ResMut<Assets<Map>>
) {
  for map_handle in map_layers.iter() {
    let map = materials.get_mut(map_handle).unwrap();

  for (position, mut transform) in entities.iter_mut() {
    let p = map.map_to_world_3d( position.position.as_vec2().extend(0.0));
    *transform = Transform::from_xyz(p.x, p.y, 250.0);
  }

  }
}

// Set cover type from map data
fn update_cover_type(
  mut entities: Query<(&MapPosition, &mut CoverType), Changed<MapPosition>>,
  map_layers: Query<&Handle<Map>>,
  mut materials: ResMut<Assets<Map>>
) {
  for map_handle in map_layers.iter() {
    let map = materials.get_mut(map_handle).unwrap();

  for (position, mut cover_type) in entities.iter_mut() {
    *cover_type = match map.intexer_mut().get_uvec(position.position) {
       0 => CoverType::NONE,
       1 => CoverType::GRASS,
       _ => CoverType::ROCK
    };
  }

  }
}```

**Comment by Droggelbecher** [comment]
Not tested for compilability but hope it illustrates the idea:
* You make entities for whatever you need in the ECS and track their position on the map with some component
* Then you write systems that query the map for whatever info you need that i.e. their world position, map contents etc...

Does this make it clearer?

**Comment by Droggelbecher** [comment]
PS: I'm iterating through all map layers here which does not make a whole lot of sense, in practice you probably have only one map layer that has the interesting information, so you might want to use something like the .single() method of bevys Query to get that.

**Comment by Mergpijp** [comment]
ok its not really applicable but i do need to remove the entity and sprite from the map after battle. the Changed thingy is triggered on change? i have a struct enemy with then its position lets say uvec2 so i set this in setup now if i need to check if my character moved to that position maybe i should make it a resource? then the screen changes battle commences. hmm

**Comment by Droggelbecher** [comment]
Well if there is only exactly one enemy make it a resource, if there can be more, make it a component (and use a query to find all the enemy entities).

While I enjoy these discussions, I fell compelled to add: We're discussing real bevy basics here and this is not the right place. Please check out bevy cheatbook, the bevy examples or the many other resources/tutorials on the internet first so we can keep this place specific the bevy-fast-tilemap.

**Comment by Mergpijp** [comment]
Okay, i kind of solved it just one issue with multiple active cameras but I think i got this. Thank you
