### ISSUE TITLE
transitioning back to tilemap with the correct mouse cursor

### ISSUE THREAD

**Issue by Mergpijp** [Droggelbecher/bevy-fast-tilemap#42]
Hi,

I used your example iso.rs the function higlight_covered does all my mouse logic. However If i go from tilemap to my battle seen and the complete it and go back, the cursor and the highlighted tile is not aligned. I tried sending a cursor moved event but to no avail. Do you know any way to fix this?

**Comment by Mergpijp** [comment]
It seems related to maximizing window as i go into battle i maximize the window (set currently to windowed) if i go back i have to put the window in previous state then the cursor is aligned with the hover. I tried doing fullscreen so i dont do any maximazation/minimazation. But after returning to map the problem persist.

**Comment by Droggelbecher** [comment]
Hey Mergpijp, can you please provide a minimal example that reproduces the error? Otherwise its really hard for me to figure out what even the problem is.

**Comment by Mergpijp** [comment]
Okay I will.
I think the problem lies with transitioning from states. So I despawn and make invisible the tile map. 
`pub fn clear_remaining_two(
    mut query2: Query<&mut Visibility, With<AnimationLayer>>,
) {
    for mut visible in query2.iter_mut() {
        *visible = Visibility::Hidden;
    }
}` and in the setup i make the map:
`pub fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<Map>>,
    icon_files: Res<IconFiles>,
) {
    let mut camera = Camera2dBundle::default();
    camera.camera.order = 0;
    camera.projection.scaling_mode = ScalingMode::AutoMin {
        min_width: 1820.0,
        min_height: 920.0,
    };
    let p_c: Vec2 = vec2(20.0, 20.0);
    let bunny: Vec2 = vec2(17.5, 16.5);
    let town1_1: Vec2 = vec2(20.0, 21.0);
    let town1_2: Vec2 = vec2(19.0, 21.0);
    let town1_3: Vec2 = vec2(20.0, 22.0);
    let town1_4: Vec2 = vec2(19.0, 22.0);
    commands.spawn(camera).insert(PrimaryCamera);
    let mut map = Map::builder(uvec2(64, 64), asset_server.load("iso_holder.png"), vec2(40., 20.))
        .with_projection(AXONOMETRIC)
        .build();

    let mut m = map.indexer_mut();

    let x_map = p_c.x + 0.5;
    let y_map = p_c.y + 0.5;

    let coord = m.map_to_local(vec2(x_map, y_map));
    let x_char = coord.x;
    let y_char = coord.y;

    let coord_e = m.map_to_local(bunny);
    let x_b = coord_e.x;
    let y_b = coord_e.y;

    let town_coord = m.map_to_local(vec2(19.9, 22.0));

    reset_map(&mut m, p_c, true, None);
    let bundle = MapBundleManaged {
        material: materials.add(map),
        transform: Transform::default().with_translation(vec3(0., 0., 0.)),
        ..default()
    };


    let texture = asset_server.load("character.png");
    commands.spawn((
        SpriteBundle {
            transform: Transform { translation: vec3(x_char, y_char, 1.), ..Default::default() },//Transform::from_scale(Vec3::splat(1.0)).with_translation(vec3(x_char, y_char, 1.)),
            texture,
            ..default()
        },
        Player {
            speed: 100.0,
            x: p_c.x,
            y: p_c.y,
            coord: None,
            coord_v: 0,
            coord_c: None,
            movement: 10,
            path: None,
        },
        Name::new("Player"),
    )).insert(AnimationLayer);

    let texture = asset_server.load("enemy_bunny.png");

    commands.spawn((
        SpriteBundle {
            transform: Transform::from_scale(Vec3::splat(1.0)).with_translation(vec3(x_b, y_b, 1.)),
            texture,
            ..default()
        },
        Enemy {position: vec2(bunny.x, bunny.y), enemy_type:CharacterType::Bunny},
        Name::new("Enemy"),
    )).insert(AnimationLayer);

    let texture = asset_server.load("friendly_town.png");

    // Load the image
    let texture2 = asset_server.load("friendly_town_h.png");

    // Create and populate the resource
    commands.insert_resource(MySprites {
        town_f: texture,
        town_fh: texture2,
        // Add other sprite handles here
    });

    let texture = asset_server.load("friendly_town.png");

    commands
        .spawn((
            SpriteBundle {
                transform: Transform::from_scale(Vec3::splat(1.0)).with_translation(vec3(town_coord.x, town_coord.y, 1.)),
                texture,
                ..default()
            },
            // Name::new("Town"),
        ))
        .insert(Town {
            coords: vec![town1_1, town1_2, town1_3, town1_4],
        }).insert(AnimationLayer);
    commands.spawn(bundle).insert(AnimationLayer);`
    I can continue where I insert AnimationLayer also to the townboard UI.  When I go back to the running state the game is not the same anymore the hovering of the map is glitched and the cursor does not follow the highlight_hover even if i send a mouseevent with a delta because i stored the old mouse position: 
    `    for (entity, enemy, last_pos) in query3.iter_mut() {
        for mut player in query4.iter_mut() {
            player.x = enemy.position.x;
            player.y = enemy.position.y; 
            let en = window_query.get_single().unwrap();
            let window = q_window.single();
            let cur_pos = window.cursor_position().unwrap();
            let dx = (last_pos.0.x - cur_pos.x).abs();
             let dy = (last_pos.0.y - cur_pos.y).abs();
            cursor_moved_events.send(CursorMoved {
                window: en,
                position: cur_pos,
                delta:  Some(vec2(dx, dy)), // You can set the delta if needed
            });
            commands.entity(entity).despawn();
        }
    } `
    with query3:
    `mut query3: Query<(Entity, &Enemy, &LastMousePos), (With<AnimationLayer>, With<SelectedEnemy>)>,`
    Will an event trigger if it is not yet in the state? later i change state to running again.
    Thank you hope this helps

**Comment by Mergpijp** [comment]
Hi sorry for taking up your time the culprit was the change in scaling

        camera.projection.scaling_mode = ScalingMode::AutoMin {
            min_width: 1820.0,
            min_height: 920.0,
        };

i had for the map and not for the battle.
that messed up things.
