### ISSUE TITLE
Publishing 0.8.1 to crates.io?

### ISSUE THREAD

**Issue by newclarityex** [Droggelbecher/bevy-fast-tilemap#53]
0.7.6 is the latest release shown on crates.io currently, is there a reason why 0.8+ versions aren't included?

**Comment by Droggelbecher** [comment]
Oversight on my side, will fix it as soon as I can get back to my private PC (prolly weekend or some time next week)

**Comment by Droggelbecher** [comment]
Should be all there now :)
